name: V1_BuildAndDeploy_PythonApp_ToAzureWebApp

on:
  push:
    paths:
      - sampleApps/python/**
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v1 version
      uses: Azure/appservice-build@v1
      with:
        source-directory: sampleApps/python/django-app
        platform: python
        platform-version: 3.7

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v1-python-sampleapp
        publish-profile: ${{ secrets.v1PythonSampleApp }}
        package: sampleApps/python/django-app
