name: V2_BuildAndDeploy_AspNetCoreReactApp_ToAzureWebApp

on:
  repository_dispatch:
  push:
    paths:
      - sampleApps/multiPlatform/dotnetreact/**
      - '!.github/workflows/**'
      - '.github/workflows/v2.deployDotNetCoreReactAppToAzureWebApp.yml'
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2 version
      uses: Azure/appservice-build@v2
      with:
        source-directory: sampleApps/multiPlatform/dotnetreact
        platform: dotnet
        platform-version: 3.1
        output-directory: sampleApps/multiPlatform/dotnetreact/output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v2-dotnetcorereact-sampleapp
        publish-profile: ${{ secrets.v2DotNetCoreReactSampleApp }}
        package: sampleApps/multiPlatform/dotnetreact/output
