name: V2Beta_BuildAndDeploy_PythonApp_ToAzureWebApp

on:
  push:
    paths:
      - sampleApps/python/**
      - '!.github/workflows/**'
      - '.github/workflows/v2beta.deployPythonAppToAzureWebApp.yml'
    branches:
      - master
      - actions/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2-beta version
      uses: Azure/appservice-build@v2-beta
      with:
        source-directory: sampleApps/python/django-app
        platform: python
        platform-version: 3.7

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v2beta-python-sampleapp
        publish-profile: ${{ secrets.v2betaPythonSampleApp }}
        package: sampleApps/python/django-app
