name: V2Beta_BuildAndDeploy_AspNetCoreApp_ToAzureWebApp

on:
  push:
    paths:
      - sampleApps/dotNetCore/NetCoreApp31.MvcApp/**
      - '!.github/workflows/**'
      - '.github/workflows/v2beta.deployDotNetCoreAppToAzureWebApp.yml'
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2-beta version
      uses: Azure/appservice-build@kichalla/v2-beta
      with:
        source-directory: sampleApps/dotNetCore/NetCoreApp31.MvcApp
        platform: dotnet
        platform-version: 3.1
        output-directory: sampleApps/dotNetCore/NetCoreApp31.MvcApp/output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v2beta-dotnetcore-sampleapp
        publish-profile: ${{ secrets.v2betaDotNetCoreSampleApp }}
        package: sampleApps/dotNetCore/NetCoreApp31.MvcApp/output
