name: V2Beta_BuildAndDeploy_NodeApp_ToAzureWebApp

on:
  push:
    paths:
      - sampleApps/node/**
      - '!.github/workflows/**'
      - '.github/workflows/v2beta.deployNodeAppToAzureWebApp.yml'
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2-beta version
      uses: Azure/appservice-build@v2-beta
      with:
        source-directory: sampleApps/node/angularsample
        platform: nodejs
        platform-version: 12

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: v2beta-node-sampleapp
        publish-profile: ${{ secrets.v2betaNodeSampleApp }}
        package: sampleApps/node/angularsample
