on:
  schedule:
    - cron: '*/2 * * * *'    
  push:
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2-beta version
      uses: Azure/appservice-build@kichalla/use.cdn
      with:
        source-directory: sampleApps/python/django-app
        platform: python
        platform-version: 3.8